name: phonebox_ui
description: PhoneBoxUI
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_html: ^3.0.0

  # WebRTC
  flutter_webrtc: ^1.2.0

  # Socket.IO for Flutter Web
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
